In [1]:
import pandas as pd

In [2]:
data = {
    "Name" :["John", "Peter", "Tony", "Sachi", "Subash", "Kanha", "Prakash"],
    "Age" :[25,27,30,32,35,38,40],
    "Salary" :[20000,25000,30000,35000,40000,45000,50000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
print(df)

      Name  Age  Salary
0     John   25   20000
1    Peter   27   25000
2     Tony   30   30000
3    Sachi   32   35000
4   Subash   35   40000
5    Kanha   38   45000
6  Prakash   40   50000

In [5]:
df.head(3)

    Name  Age  Salary
0   John   25   20000
1  Peter   27   25000
2   Tony   30   30000

In [6]:
df.tail(2)

      Name  Age  Salary
5    Kanha   38   45000
6  Prakash   40   50000

In [8]:
df.describe()

             Age        Salary
count   7.000000      7.000000
mean   32.428571  35000.000000
std     5.563486  10801.234497
min    25.000000  20000.000000
25%    28.500000  27500.000000
50%    32.000000  35000.000000
75%    36.500000  42500.000000
max    40.000000  50000.000000

In [9]:
x=[1,2,3,4,5]
var = pd.Series(x,index=['a','b','c','d','e'],dtype="float")
print(var)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64