# Write CSV

In [1]:
import pandas as pd

dis = {"A":[1,2,3,4,5,6],"B":[1,2,3,4,5,6],"C":[1,2,3,4,5,6]}
d = pd.DataFrame(dis)
print(d)
d.to_csv("Test_new.csv")

   A  B  C
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  6  6

# Read CSV

In [2]:
import pandas as pd
csv_1 = pd.read_csv("Test_new.csv")
csv_1

   Unnamed: 0  A  B  C
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [3]:
csv_2 = pd.read_csv("Test_new.csv",nrows=3)
csv_2

   Unnamed: 0  A  B  C
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3

In [4]:
csv_2 = pd.read_csv("Test_new.csv",usecols=["A"])
csv_2

   A
0  1
1  2
2  3
3  4
4  5
5  6

In [5]:
csv_2 = pd.read_csv("Test_new.csv",skiprows=[2])
csv_2

   Unnamed: 0  A  B  C
0           0  1  1  1
1           2  3  3  3
2           3  4  4  4
3           4  5  5  5
4           5  6  6  6

In [6]:
csv_2 = pd.read_csv("Test_new.csv",index_col=["A"])
csv_2

   Unnamed: 0  B  C
A
1           0  1  1
2           1  2  2
3           2  3  3
4           3  4  4
5           4  5  5
6           5  6  6

In [7]:
csv_2 = pd.read_csv("Test_new.csv",header=[5])
csv_2

   4  5  5.1  5.2
0  5  6    6    6

In [8]:
csv_2 = pd.read_csv("Test_new.csv", header= None)
csv_2.columns = ["col1","col2","col3","col4"]
csv_2

   col1 col2 col3 col4
0   NaN    A    B    C
1   0.0    1    1    1
2   1.0    2    2    2
3   2.0    3    3    3
4   3.0    4    4    4
5   4.0    5    5    5
6   5.0    6    6    6