# Pandas Function

In [1]:
import pandas as pd
csv_1 = pd.read_csv(r"C:\Users\sachi\Pandas_jupyter\Test_new.csv")
csv_1

   Unnamed: 0  A  B  C
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [2]:
csv_1.index

RangeIndex(start=0, stop=6, step=1)

In [3]:
csv_1.columns

Index(['Unnamed: 0', 'A', 'B', 'C'], dtype='str')

In [4]:
csv_1.describe()

       Unnamed: 0         A         B         C
count    6.000000  6.000000  6.000000  6.000000
mean     2.500000  3.500000  3.500000  3.500000
std      1.870829  1.870829  1.870829  1.870829
min      0.000000  1.000000  1.000000  1.000000
25%      1.250000  2.250000  2.250000  2.250000
50%      2.500000  3.500000  3.500000  3.500000
75%      3.750000  4.750000  4.750000  4.750000
max      5.000000  6.000000  6.000000  6.000000

In [5]:
csv_1.head(2)

   Unnamed: 0  A  B  C
0           0  1  1  1
1           1  2  2  2

In [6]:
csv_1.tail(3)

   Unnamed: 0  A  B  C
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [7]:
csv_1[:2]

   Unnamed: 0  A  B  C
0           0  1  1  1
1           1  2  2  2

In [8]:
csv_1[1:5]

   Unnamed: 0  A  B  C
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5

In [9]:
csv_1.index.array

<NumpyExtensionArray>
[0, 1, 2, 3, 4, 5]
Length: 6, dtype: int64

In [10]:
csv_1.to_numpy

<bound method DataFrame.to_numpy of    Unnamed: 0  A  B  C
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6>

In [11]:
csv_1.sort_index(axis=0,ascending=False)

   Unnamed: 0  A  B  C
5           5  6  6  6
4           4  5  5  5
3           3  4  4  4
2           2  3  3  3
1           1  2  2  2
0           0  1  1  1

In [12]:
csv_1.sort_index(axis=1,ascending=False)

   Unnamed: 0  C  B  A
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [13]:
csv_1["A"] = csv_1["A"].astype(str)
csv_1.loc[0,"A"] = "python"
csv_1

   Unnamed: 0       A  B  C
0           0  python  1  1
1           1       2  2  2
2           2       3  3  3
3           3       4  4  4
4           4       5  5  5
5           5       6  6  6

In [14]:
csv_1.loc[[4],["C"]]

   C
4  5

In [15]:
csv_1.loc[:,["B"]]

   B
0  1
1  2
2  3
3  4
4  5
5  6

In [16]:
csv_1.loc[[5],:]

   Unnamed: 0  A  B  C
5           5  6  6  6

In [17]:
csv_1.iloc[3,2]

np.int64(4)

In [18]:
csv_1.drop(0,axis=0)

   Unnamed: 0  A  B  C
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [19]:
csv_1.drop("A",axis=1)

   Unnamed: 0  B  C
0           0  1  1
1           1  2  2
2           2  3  3
3           3  4  4
4           4  5  5
5           5  6  6